### ISSUE TITLE
Retrieve notifications not working

### ISSUE THREAD

**Issue by nitanta** [3dsinteractive/pam-sdk-swift#12]
According, to the PAM ios sdk  , this is the api being called for loading notifications
```https://pam-api.****.com/api/app-notifications/?_database=****-registered&_contact_id=*********&customer=************```
for  this, I do not receive any data.

However, if I try  using this api in postman
```https://pam-api.****.com/api/app-notifications?_database=****&_contact_id=**********&customer=*********```
I receive the desired response. 

The only difference between the two apis is ```/```  after  app-notifications

**Comment by heart** [comment]
Thankyou @nitanta 

I fixed it in version 1.4.7
